<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.minestorm.party</groupId>
    <artifactId>minestormparty-parent</artifactId>
    <version>1.0.0</version>
  </parent>
  <artifactId>minestormparty-bungee</artifactId>
  <name>MineStormParty-Bungee</name>

  <dependencies>
    <dependency>
      <groupId>com.minestorm.party</groupId>
      <artifactId>minestormparty-common</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>net.md-5</groupId>
      <artifactId>bungeecord-api</artifactId>
      <version>1.20-R0.1-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>

  <repositories>
    <repository>
      <id>bungeecord-repo</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
  </repositories>

  <build>
    <finalName>MineStormParty-Bungee-${project.version}</finalName>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>
  </build>
</project>
