<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.minestorm.party</groupId>
    <artifactId>minestormparty-parent</artifactId>
    <version>1.0.0</version>
  </parent>
  <artifactId>minestormparty-velocity</artifactId>
  <name>MineStormParty-Velocity</name>

  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.minestorm.party</groupId>
      <artifactId>minestormparty-common</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.velocitypowered</groupId>
      <artifactId>velocity-api</artifactId>
      <version>3.3.0-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>

  <repositories>
    <repository>
      <id>papermc</id>
      <url>https://repo.papermc.io/repository/maven-public/</url>
    </repository>
  </repositories>

  <build>
    <finalName>MineStormParty-Velocity-${project.version}</finalName>
  </build>
</project>
